---
hostname: vm01
domainname: example.com

# manual configuration of network
disable_dhcp: false
ipaddress: 192.168.1.2
gateway: 192.168.1.1
dnsservers: "8.8.8.8"
netmaks: 255.255.255.0

# xenserver details
vm_name: "vm01"
network_name: "Pool-wide network associated with eth0"
sr_name: "Local storage"
vm_template: "Ubuntu Precise Pangolin 12.04 (64-bit)"
os_iso: "ubuntu-12.04.5-server-amd64.iso"

# geometry of the VM
vcpu_count: 1
cpu_weight: 64
memory: 1073741824
disksize: 26843545600
runtime_environment: testing

# link to ubuntu preseed file
preseed_url: http://10.127.1.209/files/preseed.cfg

# Boot args
auto_boot_args: '--- quiet console=hvc0 auto=true url={{ preseed_url }} hostname={{ hostname }} domain={{ domainname }} interface={{ interface | default("eth0") }} locale=en_US console-setup/ask_detect=false locale=en_US.UTF-8 DEBCONF_INTERFACE=noninteractive priority=critical environment={{ runtime_environment | default("production") }}'
man_boot_args: '--- quiet console=hvc0 auto=true url={{ preseed_url }} hostname={{ hostname }} domain={{ domainname }} interface={{ interface | default("eth0") }} netcfg/disable_autoconfig=true netcfg/get_ipaddress={{ ipaddress }} netcfg/get_netmask={{ netmask | default("255.255.255.0") }} netcfg/get_gateway={{ gateway }} netcfg/get_nameservers="{{ dnsservers }}" locale=en_US console-setup/ask_detect=false locale=en_US.UTF-8 DEBCONF_INTERFACE=noninteractive priority=critical environment={{ runtime_environment | default("production") }}'
